# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7df60df106c164aff375698cdec30d77a13dc7750181603f82b0c0af7a44db162bf0f34b8fe2dc023a206d7995a707c20b91a56c3d9ad7614d4020c8276b8b73

test:
  secret_key_base: b084a4665960b21cad2073d18a5a6b63f1d7bdb01f97f9011429a45943d427b69eecccfdda78fe07587994759938af9bfe8a13b6c1eea0452778f1106371d3e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
